// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/24/2024, 6:04:04 PM
const configMerger = require("/Users/kodaas/ezeagency/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kodaas/ezeagency/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/plugins/**/*.{js,ts,mjs}","/Users/kodaas/ezeagency/composables/**/*.{js,ts,mjs}","/Users/kodaas/ezeagency/utils/**/*.{js,ts,mjs}","/Users/kodaas/ezeagency/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kodaas/ezeagency/app.config.{js,ts,mjs}"] }));

module.exports = config
